language: ruby
before_install: gem install bundler -v '~> 1.9'
cache: bundler
rvm:
  - 2.1.3
  - 2.2.1
before_script:
  - mysql -e 'create database activerecord_view_test'
  - psql -c 'create database activerecord_view_test' -U postgres
addons:
  postgresql: "9.3"
